### ISSUE TITLE
Client doesn't set Content-Type header resulting in warnings on Crate

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate_adapter#1]
Starting with 2.1 CrateDB emits a warning in the log if a HTTP client doesn't specify the `Content-Type` header. (It should be set to application/json on requests to `/_sql`).

It appears that this client doesn't set it. (Tested with a version built from August 7th - but the commits after that don't affect any http-client related code as far as I've seen)

```
[WARN ][o.e.d.r.RestController   ] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.
```

**Comment by jodok** [comment]
fixed by #2
