### ISSUE TITLE
CrateDB 3.1.0

### ISSUE THREAD

**Issue by drewhemm** [crate/crate_adapter#18]
Hi,

The readme says that 3.1.0 or greater is required, but the latest available version is 3.0.3:

https://crate.io/download/

**Comment by drewhemm** [comment]
Ah, I see 3.1.0 is the latest nightly build.

**Comment by fabianbaier** [comment]
When running this with `3.1.1` I get:

```
time="2019-09-10T02:47:21Z" level=error msg="Failed to POST inserts to Crate." err="error preparing write statement: ERROR: SchemaUnknownException: Schema 'prometheus' unknown (SQLSTATE XX000)" source="server.go:332"
```

Shouldn't it work?
