### ISSUE TITLE
mismatched input 'commit'

### ISSUE THREAD

**Issue by lstanczak** [crate/crate_adapter#19]
When using  prometheus 2.3.2 and crate 3.0.5 I'm getting:

ERRO[2772] Failed to POST inserts to Crate.              err="error closing write batch: ERROR: SQLParseException: line 1:1: mismatched input 'commit' expecting {'SELECT', 'DEALLOCATE', 'CREATE', 'ALTER', 'KILL', 'BEGIN', 'EXPLAIN', 'SHOW', 'OPTIMIZE', 'REFRESH', 'RESTORE', 'DROP', 'INSERT', 'DELETE', 'UPDATE', 'SET', 'RESET', 'COPY', 'GRANT', 'DENY', 'REVOKE'} (SQLSTATE XX000)" source="server.go:332"

**Comment by calbinson** [comment]
Noticed you closed this? I'm getting the same output using Prometheus 2.3.2 and Crate 3.0.5, did you find a workaround?

**Comment by lstanczak** [comment]
Yes, you need to use nigthly build of crate (3.1.0).

**Comment by calbinson** [comment]
Thank you.
