### ISSUE TITLE
Failed to POST inserts to Crate.  err="error closing write batch

### ISSUE THREAD

**Issue by nickmy9729** [crate/crate_adapter#22]
Receiving this when writing metrics to crateDB version 3.0.3.

Failed to POST inserts to Crate.              err="error closing write batch: ERROR: SQLParseException: line 1:1: mismatched input 'commit' expecting {'SELECT', 'DEALLOCATE', 'CREATE', 'ALTER', 'KILL', 'BEGIN', 'EXPLAIN', 'SHOW', 'OPTIMIZE', 'REFRESH', 'RESTORE', 'DROP', 'INSERT', 'DELETE', 'UPDATE', 'SET', 'RESET', 'COPY', 'GRANT', 'DENY', 'REVOKE'} (SQLSTATE XX000)" source="server.go:332"

Looks like metrics are going in, but I am assuming some of them are being dropped.

**Comment by ykorikk** [comment]
The same behavior with CrateDB version 3.0.5

**Comment by nickmy9729** [comment]
I am going to try against the nightly build of crateDB to see if this is an issue with the version of crate not being 3.1.0.  I will post back once I have results

**Comment by seut** [comment]
I'm not really into the crate_adapter code, but support for `COMMIT` and `BEGIN` statements was recently added to the master(nightly). Also these are just ignored, see https://github.com/crate/crate/commit/4377aba4f154e67d9cad2c1eb1a21e9a029c998c.

**Comment by nickmy9729** [comment]
That makes sense.  I will know for sure once I execute the adapter against nightly build.

**Comment by nickmy9729** [comment]
Confirmed this is not an issue when using the 3.1.0 nightly build.  I am closing issue.
