### ISSUE TITLE
Binary distribution / Docker container 

### ISSUE THREAD

**Issue by hagzag** [crate/crate_adapter#3]
Is there any plan of producing these?

**Comment by joemoe** [comment]
hi @hagzag, 

the binaries can be found here: https://cdn.crate.io/downloads/dist/prometheus/
at the moment there is no plan of creating a docker container.

**Comment by hagzag** [comment]
Great thanks -> here is an Ansible role which will install it as part pf Prometheus if anyone's interested -> https://github.com/shelleg/ansible-role-prometheus
